services:
  web:
    image: ghcr.io/fasih1712/thesiscraftmentors:latest
    container_name: thesiscraftmentors
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
